### ISSUE TITLE
Unable to login via SSO on Linux (AppImage only)

### ISSUE THREAD

**Issue by rkujawa** [bitwarden/cli#165]
It seems that bw is unable to open the browser.

This is on a bw 1.12.0, downloaded from releases page.

```
$ ./bw login --sso
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/cli/node_modules/open/xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by kspearrin** [comment]
Could you provide more info so that we can try to reproduce the issue? What distro? Is this headless? What browser?

**Comment by rkujawa** [comment]
Fedora 32, default shipped browser (firefox-80.0.1-2.fc32.x86_64). It's a normal GUI session with GNOME.

**Comment by rkujawa** [comment]
Btw. the desktop application can open the browser just fine, but has a different issue related to this process: https://github.com/bitwarden/desktop/issues/551 .

**Comment by kspearrin** [comment]
On the CLI, we are using the `open` library to launch the browser from a node process.

https://github.com/sindresorhus/open

https://github.com/bitwarden/jslib/blob/master/src/cli/commands/login.command.ts#L253

Are you able to test to see if that library works for your environment?

**Comment by kspearrin** [comment]
Here's `open`'s implementation for Linux:

https://github.com/sindresorhus/open/blob/master/index.js#L100

**Comment by rkujawa** [comment]
The library itself seems to work fine if installed by hand. Since that worked okay, I decided to do

```
npm install @bitwarden/cli
```

This has resulted in a working installation:
```
$ node_modules/@bitwarden/cli/build/bw.js login --sso
You are logged in!
(...)
```

Therefore, I assume the source of original problem lies in how AppImage packages xdg-open, or how the `open` library uses xdg-open in a "packed" application?

**Comment by kspearrin** [comment]
@rkujawa Can you try the linux binary from this dev build to see if it works now?

https://ci.appveyor.com/project/bitwarden/cli/builds/35342125/job/2sxc3r4slxibgie7/artifacts

**Comment by rkujawa** [comment]
@kspearrin This build causes a segfault...

```
$ ./bw 
Segmentation fault (core dumped)
```

Unfortunately, my JavaScript knowledge is null, I don't know how to further debug this. GDB does not give any promising results...

```
$ gdb bw
GNU gdb (GDB) Fedora 9.1-6.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bw...
(gdb) run
Starting program: /home/rkujawa/Downloads/bw 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.31-4.fc32.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff7a52700 (LWP 41630)]
[New Thread 0x7ffff7251700 (LWP 41631)]
[New Thread 0x7ffff6a50700 (LWP 41632)]
[New Thread 0x7ffff624f700 (LWP 41633)]
[New Thread 0x7ffff5a4e700 (LWP 41634)]

Thread 1 "bw" received signal SIGSEGV, Segmentation fault.
0x0000000001154db4 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::GetBackReferencedObject(int) ()
(gdb) bt
#0  0x0000000001154db4 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::GetBackReferencedObject(int)
    ()
#1  0x0000000001156534 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#2  0x0000000001156023 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#3  0x0000000001156b76 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#4  0x0000000001156023 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#5  0x0000000001156bb1 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#6  0x0000000001156023 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
#7  0x0000000001156bb1 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadData(v8::internal::MaybeObject**, v8::internal::MaybeObject**, int, unsigned long) ()
#8  0x0000000001156023 in v8::internal::Deserializer<v8::internal::DefaultDeserializerAllocator>::ReadObject(int, v8::internal::MaybeObject**, v8::internal::HeapObjectReferenceType) ()
(...)
```

**Comment by kspearrin** [comment]
@rkujawa Can you try this build? https://ci.appveyor.com/project/bitwarden/cli/builds/35365981/job/vip33c6aj9tvypk5/artifacts

**Comment by rkujawa** [comment]
@kspearrin It works!

```
$ ./bw login --sso
You are logged in!

To unlock your vault, use the `unlock` command. ex:
$ bw unlock

$ ./bw unlock
? Master password: [hidden]
Your vault is now unlocked!
```
