### ISSUE TITLE
Issue running bw from systemd service

### ISSUE THREAD

**Issue by broizter** [bitwarden/cli#381]
I'm on the latest bitwarden-cli. Using the pre-compiled binary from GitHub (bw-linux-1.18.1). Running bw normally, or even from cron works as expected, but as soon as I try to run bw from a systemd service it fails with this error:

```internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1110:7)
    at new bw_Main (/snapshot/cli/build/bw.js:31553:39)
    at Module.<anonymous> (/snapshot/cli/build/bw.js:31642:14)
    at __webpack_require__ (/snapshot/cli/build/bw.js:21:30)
    at /snapshot/cli/build/bw.js:85:18
    at Object.<anonymous> (/snapshot/cli/build/bw.js:88:10)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}```

The exact command being ran is bw login --check.

**Comment by StevenMassaro** [comment]
This is still an issue with 1.20.0

**Comment by devlom113** [comment]
I was wondering if there was a workaround?

**Comment by broizter** [comment]
One workaround is to put bw inside a container and interface with it that way, that's what I've done at least. Couldn't find a simpler workaround unfortunately.

**Comment by devlom113** [comment]
In my use case it's basically running from a Service within the Laravel framework, so the issue arises when using the Symfony Process object from the application itself. My workaround is running the command as a cronjob from the system. But it's a bit tedious unfortunately.

**Comment by jkupferer** [comment]
We were just facing a similar issue when writing an Ansible lookup plugin that uses the bitwarden CLI. We found the issue was that we weren't passing the `HOME` environment variable. Further investigation revealed that the Bitwarden CLI may require `APPDATA` and `XDG_CONFIG_HOME` depending on the system it is running on.

Alternatively, you can set the environment variable `BITWARDENCLI_APPDATA_DIR` as a workaround.

**Comment by broizter** [comment]
> We were just facing a similar issue when writing an Ansible lookup plugin that uses the bitwarden CLI. We found the issue was that we weren't passing the `HOME` environment variable. Further investigation revealed that the Bitwarden CLI may require `APPDATA` and `XDG_CONFIG_HOME` depending on the system it is running on.
> 
> Alternatively, you can set the environment variable `BITWARDENCLI_APPDATA_DIR` as a workaround.

This was the fix for my specific issue! I will close the issue for now then.
